use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("build.rs");
    let mod_path = Path::new(&out_dir).join("build_mod.rs");

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    let datetime = chrono::DateTime::<chrono::Utc>::from_timestamp(now.as_secs() as i64, 0)
        .unwrap_or_default();

    let build_date = datetime.format("%Y-%m-%d").to_string();
    let build_time = datetime.format("%H:%M:%S").to_string();

    // 获取 git 版本信息
    let git_version = get_git_version();
    let git_commit_short = get_git_commit_short();

    // 生成 build.rs 供 include!
    let content = format!(
        r#"// This file is auto-generated by build.rs
pub const BUILD_DATE: &str = "{}";
pub const BUILD_TIME: &str = "{}";
pub const GIT_VERSION: &str = "{}";
pub const GIT_COMMIT_SHORT: &str = "{}";
"#,
        build_date, build_time, git_version, git_commit_short
    );

    fs::write(&dest_path, &content).unwrap();
    fs::write(&mod_path, &content).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=.git/index");
}

/// 获取 git 版本信息（tag 或 commit hash）
fn get_git_version() -> String {
    // 首先尝试获取最新 tag
    let output = Command::new("git")
        .args(["describe", "--tags", "--always", "--abbrev=7"])
        .output();

    match output {
        Ok(output) => {
            if output.status.success() {
                String::from_utf8_lossy(&output.stdout).trim().to_string()
            } else {
                // 如果没有 tag，使用 commit hash
                get_git_commit_hash()
            }
        }
        Err(_) => get_git_commit_hash(),
    }
}

/// 获取完整 commit hash
fn get_git_commit_hash() -> String {
    let output = Command::new("git").args(["rev-parse", "HEAD"]).output();

    match output {
        Ok(output) => {
            if output.status.success() {
                String::from_utf8_lossy(&output.stdout).trim().to_string()
            } else {
                "unknown".to_string()
            }
        }
        Err(_) => "unknown".to_string(),
    }
}

/// 获取短 commit hash
fn get_git_commit_short() -> String {
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output();

    match output {
        Ok(output) => {
            if output.status.success() {
                String::from_utf8_lossy(&output.stdout).trim().to_string()
            } else {
                "unknown".to_string()
            }
        }
        Err(_) => "unknown".to_string(),
    }
}
